services:
  - type: web
    name: diarization-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: HF_TOKEN
        value: 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
